name: Pull Request Checks
on:
  pull_request:
    branches:
      - master
      - main
    types: [ 'opened', 'synchronize' ]


jobs:
  commits:
    runs-on: ubuntu-latest
    name: Pull Request Max Commits
    steps:
      - name: Checking the max commits number
        run: |
          commitNum=${{ github.event.pull_request.commits }}
          if [[ ${commitNum} -gt 1 ]]; then
            echo -e "\nERROR: The PR has ${commitNum} commits, and please rebase it to 1.\n"
            exit 1
          fi
          
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-commit-lint@v2

  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: git diff
        run: |
          echo "::set-output name=changed_paths::$(git diff --name-only HEAD~1)"
      - name: set env
        env:
          CHANGED_PATHS: ${{ steps.check-changes.outputs.changed_paths }}
        run: echo "$CHANGED_PATHS"

  